version: '2'
services:
  db:
    image: postgres
  redis:
    image: redis
  elasticsearch:
    image: elasticsearch
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/appian
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    command: bundle exec sidekiq
    volumes:
      - .:/appian
    depends_on:
      - db
      - redis
      - elasticsearch
